# Generated by Django 3.0.5 on 2020-04-28 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csp_prog_list',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('pcode', models.CharField(max_length=4)),
                ('user_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=1000)),
                ('is_complete', models.BooleanField()),
                ('end_date', models.DateTimeField(default=datetime.datetime(2020, 4, 28, 2, 0, 22, 275963))),
            ],
            options={
                'db_table': 'prog_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('pcode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'project_code',
                'managed': False,
            },
        ),
    ]
