# Generated by Django 3.0.5 on 2020-05-09 16:35

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_prog_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csp_prog_list_qna',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('pcode', models.CharField(max_length=4)),
                ('user_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=20000)),
                ('is_complete', models.BooleanField()),
                ('end_date', models.DateTimeField(default=datetime.datetime(2020, 5, 9, 16, 35, 2, 809578))),
            ],
            options={
                'db_table': 'prog_board_qna',
                'managed': False,
            },
        ),
    ]
