# Generated by Django 3.0.5 on 2020-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_hack_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('pcode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'project_code',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='csp_hack_list',
            table='hack_board',
        ),
    ]
