# Generated by Django 3.0.5 on 2020-05-15 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_hack_board', '0004_auto_20200509_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakc_comment',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=50)),
                ('insert_date', models.DateTimeField(default=datetime.datetime(2020, 5, 15, 0, 8, 21, 768047))),
            ],
            options={
                'db_table': 'hack_comment',
                'managed': False,
            },
        ),
    ]
