# Generated by Django 3.0.5 on 2020-05-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csp_hack_board', '0005_hakc_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hakc_comment',
        ),
    ]
