# Generated by Django 3.0.5 on 2020-05-28 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_hack_board', '0006_delete_hakc_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hack_comment',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=1000)),
                ('insert_date', models.DateTimeField(default=datetime.datetime(2020, 5, 28, 22, 22, 50, 779436))),
                ('user_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hack_comment',
                'managed': False,
            },
        ),
    ]
